#!/bin/bash
APP_PATH=/var/www/farms/reviews
GIT_DIR=/var/repo/farms/reviews.git

[[ -s "/usr/local/rvm/bin/rvm" ]] && . "/usr/local/rvm/bin/rvm"

git --work-tree=${APP_PATH} --git-dir=${GIT_DIR} checkout -f
echo "==========  CODE DEPLOYED =========="

cd ${APP_PATH}
/usr/local/rvm/gems/ruby-2.0.0-p353@global/bin/bundle install --deployment
echo "==========  BUNDLED  =========="

echo "==========  MIGRATING  =========="
/usr/local/rvm/gems/ruby-2.0.0-p353/bin/rake db:migrate RAILS_ENV=production
echo "==========  MIGRATED  =========="

echo "==========  RESTARTING APP  =========="
mkdir -p tmp
touch tmp/restart.txt
echo "==========  APP RESTARTED  =========="
